### ISSUE TITLE
Request lib breaks b/c http.Agent is not implemented

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t1-runtime#277]
The `request` lib depends on [`http.Agent`](http://nodejs.org/api/http.html#http_class_http_agent) which isn't implemented yet.

**Comment by johnhrogers** [comment]
Your sample code here doesn't work as expected on my Tessel. It returns at the end of the script without logging anything to the console.

**Comment by natevw** [comment]
@johnhrogers That sounds like it might be a new/different bug then. Could you file a separate issue with any additional details that might be relevant, like request library version and `tessel version --board` info? 

[Also, make sure your WiFi is connected before trying to run any sort of network-related script, I've had some weird issues with that lately: https://github.com/tessel/firmware/issues/129]
